config/routes.rb
Rails.application.routes.draw do

  # Mounts
  # ----------------------------------------------------------------------------
  get '/console', to: 'application#console', constraints: ConsoleConstraint.new
  # ----------------------------------------------------------------------------

  # Setup Root & Admin
  # ----------------------------------------------------------------------------
  root to: 'pages#root'

  get '/admin', to: redirect("/#{I18n.locale}/admin")

  get '/:locale', to: redirect('/')
  # ----------------------------------------------------------------------------

  scope '/:locale', locale: /#{Settings['locales']['visible'].join('|')}/ do

    # User & Session
    # ----------------------------------------------------------------------------
    get  '/sign_up',  to: 'user/registrations#new',    as: :sign_up
    post '/sign_up',  to: 'user/registrations#create', as: :sign_up_post
    get  '/sign_out', to: 'user/sessions#destroy',     as: :sign_out
    get  '/sign_in',  to: 'user/sessions#new',         as: :sign_in
    post '/sign_in',  to: 'user/sessions#create',      as: :sign_in_post
    # ----------------------------------------------------------------------------

    # Admin
    # ==========================================================================
    namespace :admin do

      # Pages
      # --------------------------------------------------------------------------
      get '/', to: 'pages#dashboard'
      # --------------------------------------------------------------------------

      # Versions
      # --------------------------------------------------------------------------
      get '/version/:id', to: 'versions#show', as: :version
      # --------------------------------------------------------------------------

      # User
      # --------------------------------------------------------------------------
      get   '/users',              to: 'users#index',    as: :users
      get   '/users/:id',          to: 'users#show',     as: :user
      get   '/users/:id/edit',     to: 'users#edit',     as: :user_edit
      patch '/users/:id/edit',     to: 'users#update',   as: :user_update
      get   '/users/:id/delete',   to: 'users#delete',   as: :user_delete
      get   '/users/:id/login_as', to: 'users#login_as', as: :user_login_as
      # --------------------------------------------------------------------------

    end
    # ==========================================================================

  end
end

app/models/system/version.rb
class Version < ApplicationRecord
  extend Enumerize

  default_scope { order('created_at DESC') }

  serialize :fields_changed, Array
  serialize :body,           Hash

  enumerize :event,
            in:         I18n.t('enumerize.version.event').keys,
            i18n_scope: 'enumerize.version.event',
            predicates: {prefix: true}

  def editor
    User.find(self.editor_id) rescue nil
  end

  def model_object
    self.model.constantize
  end

  def model_instance
    self.model_object.find(self.model_id)
  end

  def previous
    self
      .model_instance
      .versions
      .where('versions.created_at < ?', self.created_at)
      .order('created_at DESC').first
  end

end

app/controllers/admin/versions_controller.rb
class Admin::VersionsController < Admin::ApplicationController

  def show
    @version = Version.find(params[:id])

    if can?(:view_versions, User)
      @previous = @version.previous
    else
      redirect_to admin_path
    end
  end

end

app/helpers/versions_helper.rb
module VersionsHelper


  def versions_model_link(version)
    name = version.model + ' #' + version.model_id.to_s

    if version.model == 'User'
      link_to_if can?(:read, @version.model_instance), name, admin_user_path(version.model_id)
    else
      name
    end
  end


  def versions_editor_link(version)
    if version.editor_id
      link_to_if can?(:read, version.editor), version.editor.email, admin_user_path(version.editor)
    else
      '-'
    end
  end


  def versions_fields_changed_badges(version)
    previous = version.previous

    version.fields_changed.map do |field_changed|
      title = []
      title << previous.body[field_changed] if previous
      title << version.body[field_changed]

      content_tag(
        :span, field_changed,
        class: 'badge badge-dark',
        style: 'margin: 0 1px;',
        title: title.map { |x| "\"#{x}\"" }.join(' > ')
      )
    end.join('').html_safe
  end


end

app/views/admin/versions/partials/_list.haml
.card.mt-20
  .card-header.pt-12.pl-12
    %strong= t('admin.views.shared.versions')
  .card-title.mb-0
    .table-responsive
      %table.table.table-borderless.table-striped.mb-0
        %thead
          %tr
            %th= t('activerecord.shared.id')
            %th= t('activerecord.models.user')
            %th= t('activerecord.attributes.version.event')
            %th= t('activerecord.attributes.version.fields_changed')
            %th= t('activerecord.shared.created_at')
            %th
        %tbody
          - versions.each do |version|
            %tr
              %td= version.id
              %td= version.editor_id.nil? ? '-' : link_to(version.editor.email, admin_user_path(version.editor_id))
              %td= version.event.text
              %td= versions_fields_changed_badges(version)
              %td= version.created_at.to_s(:datetime)
              %td.actions= link_to fa_icon('eye'), admin_version_path(version), title: t('admin.views.shared.show'), class: 'btn btn-default btn-sm'

  - unless paginate(versions).blank?
    .card-footer.pt-26.pl-30= paginate @versions, theme: 'twitter-bootstrap-4'