config/routes.rb
Rails.application.routes.draw do

  # Mounts
  # ----------------------------------------------------------------------------
  get '/console', to: 'application#console', constraints: ConsoleConstraint.new
  # ----------------------------------------------------------------------------

  # Setup Root & Admin
  # ----------------------------------------------------------------------------
  root to: 'pages#root'

  get '/admin', to: redirect("/#{I18n.locale}/admin")

  get '/:locale', to: redirect('/')
  # ----------------------------------------------------------------------------

  scope '/:locale', locale: /#{Settings['locales']['visible'].join('|')}/ do

    # User & Session
    # ----------------------------------------------------------------------------
    get  '/sign_up',  to: 'user/registrations#new',    as: :sign_up
    post '/sign_up',  to: 'user/registrations#create', as: :sign_up_post
    get  '/sign_out', to: 'user/sessions#destroy',     as: :sign_out
    get  '/sign_in',  to: 'user/sessions#new',         as: :sign_in
    post '/sign_in',  to: 'user/sessions#create',      as: :sign_in_post
    # ----------------------------------------------------------------------------

    # Admin
    # ==========================================================================
    namespace :admin do

      # Pages
      # --------------------------------------------------------------------------
      get '/', to: 'pages#dashboard'
      # --------------------------------------------------------------------------

      # Versions
      # --------------------------------------------------------------------------
      get '/version/:id', to: 'versions#show', as: :version
      # --------------------------------------------------------------------------

      # User
      # --------------------------------------------------------------------------
      get   '/users',              to: 'users#index',    as: :users
      get   '/users/:id',          to: 'users#show',     as: :user
      get   '/users/:id/edit',     to: 'users#edit',     as: :user_edit
      patch '/users/:id/edit',     to: 'users#update',   as: :user_update
      get   '/users/:id/delete',   to: 'users#delete',   as: :user_delete
      get   '/users/:id/login_as', to: 'users#login_as', as: :user_login_as
      # --------------------------------------------------------------------------

    end
    # ==========================================================================

  end
end

app/views/admin/_shared/_flash_messages.haml
- if flash[:notice]
  .container{style: 'max-width: 500px; margin: 50px auto;'}
    .alert.alert-success= flash[:notice]

- if flash[:alert]
  .container{style: 'max-width: 500px; margin: 50px auto;'}
    .alert.alert-danger= flash[:alert]

app/views/admin/_shared/_header.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark

  %a.navbar-brand{href: "#"}= t('overall.name')

  %button.navbar-toggler{'aria-controls':  'navbarMainMenuContent',
                          'aria-expanded': false,
                          'data-target':   '#navbarMainMenuContent',
                          'data-toggle':   'collapse',
                          'aria-label':    'Toggle navigation',
                          type:            'button'}
    %span.navbar-toggler-icon

  #navbarMainMenuContent.collapse.navbar-collapse

    %ul.navbar-nav.mr-auto
      %li.nav-item= link_to t('views.header.links.home'),      root_path,  class: 'nav-link'
      %li.nav-item= link_to t('views.header.links.dashboard'), admin_path, class: 'nav-link'

      - if can?(:index, User)
        %li.nav-item= link_to t('views.header.links.users'), admin_users_path, class: 'nav-link'

    %ul.navbar-nav.ml-auto
      = render partial: '_shared/header_language_switch_item'

app/views/admin/_shared/_header_language_switch_item.haml
%li.nav-item.dropdown
  %a#navbarDropdown.nav-link.dropdown-toggle{'aria-expanded':  false,
                                              'aria-haspopup': true,
                                              'data-toggle':   'dropdown',
                                              href:            '#',
                                              role:            'button'}
    = t('language')
  .dropdown-menu{'aria-labelledby': 'navbarDropdown'}
    - I18n.available_locales.each do |locale|
      = link_to t("locales.#{locale}"), {locale: locale}, class: 'dropdown-item'