config/routes.rb
Rails.application.routes.draw do

  # Mounts
  # ----------------------------------------------------------------------------
  get '/console', to: 'application#console', constraints: ConsoleConstraint.new
  # ----------------------------------------------------------------------------

  # Setup Root & Admin
  # ----------------------------------------------------------------------------
  root to: 'pages#root'

  get '/admin', to: redirect("/#{I18n.locale}/admin")

  get '/:locale', to: redirect('/')
  # ----------------------------------------------------------------------------

  scope '/:locale', locale: /#{Settings['locales']['visible'].join('|')}/ do

    # User & Session
    # ----------------------------------------------------------------------------
    get  '/sign_up',  to: 'user/registrations#new',    as: :sign_up
    post '/sign_up',  to: 'user/registrations#create', as: :sign_up_post
    get  '/sign_out', to: 'user/sessions#destroy',     as: :sign_out
    get  '/sign_in',  to: 'user/sessions#new',         as: :sign_in
    post '/sign_in',  to: 'user/sessions#create',      as: :sign_in_post
    # ----------------------------------------------------------------------------

    # Admin
    # ==========================================================================
    namespace :admin do

      # Pages
      # --------------------------------------------------------------------------
      get '/', to: 'pages#dashboard'
      # --------------------------------------------------------------------------

      # Versions
      # --------------------------------------------------------------------------
      get '/version/:id', to: 'versions#show', as: :version
      # --------------------------------------------------------------------------

      # User
      # --------------------------------------------------------------------------
      get   '/users',              to: 'users#index',    as: :users
      get   '/users/:id',          to: 'users#show',     as: :user
      get   '/users/:id/edit',     to: 'users#edit',     as: :user_edit
      patch '/users/:id/edit',     to: 'users#update',   as: :user_update
      get   '/users/:id/delete',   to: 'users#delete',   as: :user_delete
      get   '/users/:id/login_as', to: 'users#login_as', as: :user_login_as
      # --------------------------------------------------------------------------

    end
    # ==========================================================================

  end
end

app/models/concerns/users/setup_blocked.rb
require 'active_support/concern'

module Users
  module SetupBlocked
    extend ::ActiveSupport::Concern

    included do


      validates :blocked_reason,
                presence: true,
                if:       -> { self.blocked }


      scope :blocked,     -> { where(blocked: true) }
      scope :not_blocked, -> { where(blocked: false) }


      before_save :clear_blocked_reason_if_not_blocked_anymore


      def clear_blocked_reason_if_not_blocked_anymore
        if self.blocked_changed? && !self.blocked?
          self.blocked_reason = nil
        end
      end


    end
  end
end

app/models/concerns/users/setup_deleted.rb
require 'active_support/concern'

module Users
  module SetupDeleted
    extend ::ActiveSupport::Concern

    included do

      scope :deleted,     -> { where(deleted: true) }
      scope :not_deleted, -> { where(deleted: false) }

    end
  end
end

app/models/concerns/users/setup_email.rb
require 'active_support/concern'

module Users
  module SetupEmail
    extend ::ActiveSupport::Concern

    included do


      validates :email,
                length:     {
                  minimum: Settings['users']['validations']['email']['min_length'],
                  maximum: Settings['users']['validations']['email']['max_length']
                },
                presence:   true,
                uniqueness: { case_sensitive: false },
                format:     /\S+@\S+\.\S+/,
                if:         Proc.new { |m| m.deleted == false }


    end
  end
end

app/models/concerns/users/setup_locale.rb
require 'active_support/concern'

module Users
  module SetupLocale
    extend ::ActiveSupport::Concern

    included do

      aasm column: :locales do
        state :en, initial: true
      end

      enumerize :locale,
                in:         I18n.t('locales').keys,
                i18n_scope: 'locales',
                predicates: { prefix: true }

    end
  end
end

app/models/concerns/users/setup_password.rb
require 'active_support/concern'

module Users
  module SetupPassword
    extend ::ActiveSupport::Concern

    included do


      attr_accessor :password

      attr_accessor :should_validate_password


      validates :password,
                length: {
                  minimum: Settings['users']['validations']['password']['min_length'],
                  maximum: Settings['users']['validations']['password']['max_length']
                },
                confirmation: true,
                if:           -> { self.should_validate_password }


      before_save :set_encrypted_password


      def password_is?(pass)
        ::BCrypt::Password.new(self.encrypted_password) == pass
      end


      private


      def set_encrypted_password
        return if self.password.nil?
        self.encrypted_password = ::BCrypt::Password.create(self.password)
      end


    end
  end
end

app/models/concerns/users/setup_permissions.rb
require 'active_support/concern'

module Users
  module SetupPermissions
    extend ::ActiveSupport::Concern

    included do


      delegate :can?, :cannot?, :to => :ability


      def ability
        @ability ||= Ability.new(self)
      end


      aasm column: :role do
        state :user, initial: true
        state :developer
      end


      enumerize :role,
                in:         I18n.t('enumerize.user.role').keys,
                i18n_scope: 'enumerize.user.role',
                predicates: { prefix: true }


    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include GenerateHashId
  include Versionable

  include Users::SetupEmail
  include Users::SetupLocale
  include Users::SetupDeleted
  include Users::SetupBlocked
  include Users::SetupPassword
  include Users::SetupPermissions

  scope :valid, -> { where(deleted: false, blocked: false) }

  private

  def set_version
    self.version_body = {
      role:               self.role,
      email:              self.email,
      deleted:            self.deleted,
      blocked:            self.blocked,
      blocked_reason:     self.blocked_reason,
      encrypted_password: self.encrypted_password
    }
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  load_and_authorize_resource


  def index
    params[:q] ||= { deleted_eq: false, blocked_eq: false }

    @q     = @users.ransack(params[:q])
    @users = @q.result(distinct: true)
    @users = @users.page(params[:page]).per(20)
  end


  def show
    @versions = @user.versions.page(params[:page]).per(20)
  end


  def edit; end


  def update
    @user.editor_id     = current_user.id
    @user.version_event = 'admin_update'

    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end


  def login_as
    session[:user_id] = @user.hash_id if can?(:login_as, @user)
    redirect_to admin_users_path
  end


  private


  def user_params
    permitted_params =  [:email, :locale]
    permitted_params += [:deleted]                  if can?(:delete, @user)
    permitted_params += [:blocked, :blocked_reason] if can?(:block, @user)

    if can? :change_user_role, params.dig(:user, :role).to_sym
      permitted_params << :role
    end

    params.require(:user).permit(permitted_params)
  end


end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :set_user,        only: [:new, :create]

  def new; end

  def create
    if @user.update(user_params)
      session[:user_id] = @user.hash_id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.new
  end

  def user_params
    params[:user] ||= {}

    params[:user][:should_validate_password] = true

    params.require(:user).permit(
      :email, :locale,
      :password, :password_confirmation,
      :should_validate_password
    )
  end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :require_user,    only: [:destroy]

  def new; end

  def create
    @user = User.not_deleted.find_by(email: params.dig(:user, :email))

    if @user
      if @user.password_is?(params.dig(:user, :password))
        if @user.blocked?
          render_blocked
        else
          sign_in
        end
      else
        render_wrong_password
      end
    else
      render_wrong_password
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def sign_in
    session[:user_id] = @user.hash_id
    redirect_to root_path
  end

  def render_blocked
    flash.now[:alert] = t('flash_messages.user.sessions.user_blocked')
    render :new
  end

  def render_wrong_password
    flash.now[:alert] = t('flash_messages.user.sessions.wrong_email_or_password')
    render :new
  end

end

app/views/admin/users/edit.haml
.mt-20
  = link_to t('admin.views.shared.all'),  admin_users_path,       class: 'btn btn-primary btn-sm' if can?(:index, @user)
  = link_to t('admin.views.shared.show'), admin_user_path(@user), class: 'btn btn-default btn-sm' if can?(:show,  @user)
  = admin_login_as_user_link(@user)


.card.mt-20
  = simple_form_for @user, url: admin_user_update_path(@user) do |f|
    .card-header.pt-12.pl-12
      %strong= t('activerecord.models.user')

    .card-title.p-20
      = f.input :email
      = f.input :role,   collection: User.role.options,   include_blank: false
      = f.input :locale, collection: User.locale.options, include_blank: false

      .mt-22= f.input :deleted, disabled: !can?(:delete, @user)

      .mt-18
        = f.input :blocked, disabled: !can?(:block,  @user)
        .js-dependent-fields{'data-checkbox-id': 'user_blocked', 'data-checkbox-value': 'true'}
          = f.input :blocked_reason, disabled: !can?(:block,  @user)

    .card-footer
      = f.submit t('admin.views.shared.save'), class: 'btn btn-success btn-sm'


.mt-20
  = link_to t('admin.views.shared.all'),  admin_users_path,       class: 'btn btn-primary btn-sm' if can?(:index, @user)
  = link_to t('admin.views.shared.show'), admin_user_path(@user), class: 'btn btn-default btn-sm' if can?(:show,  @user)
  = admin_login_as_user_link(@user)

app/views/admin/users/index.haml
.card.mt-20
  = simple_form_for(@q, url: admin_users_path, method: :get, html: {class: 'search-form'}) do |f|
    .card-header.pt-12.pl-12
      %strong= t('admin.views.shared.search')
    .card-title.p-12.pt-24
      .row
        .col-xs-12.col-sm-6.col-md-4= f.input :email_i_cont,
                            label:         t('activerecord.attributes.user.email'),
                            required:      false

        .col-xs-12.col-sm-6.col-md-2= f.input :role_eq,
                            label:         t('activerecord.attributes.user.role'),
                            required:      false,
                            collection:    User.role.options,
                            input_html:    {class: 'js-select', 'data-search': 'true'},
                            include_blank: t('admin.views.shared.all')

        .col-xs-12.col-sm-6.col-md-2= f.input :locale_eq,
                            label:         t('activerecord.attributes.user.locale'),
                            required:      false,
                            collection:    User.locale.options,
                            input_html:    {class: 'js-select', 'data-search': 'true'},
                            include_blank: t('admin.views.shared.all')

        .col-xs-12.col-sm-6.col-md-2= f.input :deleted_eq,
                            label:         t('activerecord.shared.deleted'),
                            required:      false,
                            collection:    yes_no_search_collection,
                            input_html:    {class: 'js-select', 'data-search': 'false'},
                            include_blank: t('admin.views.shared.all')

        .col-xs-12.col-sm-6.col-md-2= f.input :blocked_eq,
                            label:         t('activerecord.attributes.user.blocked'),
                            required:      false,
                            collection:    yes_no_search_collection,
                            input_html:    {class: 'js-select', 'data-search': 'false'},
                            include_blank: t('admin.views.shared.all')
    .card-footer.pl-12
      = f.submit t('admin.views.shared.search'), class: 'btn btn-primary btn-sm'
      = link_to  t('admin.views.shared.clear'), admin_users_path, class: 'btn btn-default btn-sm'


.card.mt-20
  .card-header.pt-12.pl-12
    %strong= t('admin.views.main_menu.users')
  .card-title.mb-0

    - if @users.length.zero?
      .alert.alert-info.m-12= t('admin.views.shared.no_records_found')
    - else
      .table-responsive
        %table.table.table-borderless.table-striped.mb-0.user-table
          %thead
            %tr
              %th= sort_link @q, 'id',         t('activerecord.shared.id')
              %th= sort_link @q, 'email',      t('activerecord.attributes.user.email')
              %th= sort_link @q, 'role',       t('activerecord.attributes.user.role')
              %th= sort_link @q, 'deleted',    t('activerecord.shared.deleted')
              %th= sort_link @q, 'blocked',    t('activerecord.attributes.user.blocked')
              %th= sort_link @q, 'created_at', t('activerecord.shared.created_at')
              %th
          %tbody
            - @users.each do |user|
              %tr{'data-deleted': user.deleted.to_s, 'data-blocked': user.blocked.to_s}
                %td= user.id
                %td= user.email
                %td= user.role.text
                %td= boolean_icon(user.blocked)
                %td= boolean_icon(user.deleted)
                %td= user.created_at.to_s(:datetime)
                %td.actions
                  = admin_login_as_user_link(user, icon_only: true)
                  = link_to fa_icon('eye'),    admin_user_path(user),      title: t('admin.views.shared.show'), class: 'btn btn-sm btn-default' if can?(:show,   user)
                  = link_to fa_icon('pencil'), admin_user_edit_path(user), title: t('admin.views.shared.edit'), class: 'btn btn-sm btn-success' if can?(:update, user)

  - unless paginate(@users).blank?
    .card-footer.pt-26.pl-30= paginate @users, theme: 'twitter-bootstrap-4'

app/views/admin/users/show.haml
.mt-20
  = link_to t('admin.views.shared.all'),  admin_users_path,            class: 'btn btn-sm btn-primary' if can?(:index, @user)
  = link_to t('admin.views.shared.edit'), admin_user_edit_path(@user), class: 'btn btn-sm btn-success' if can?(:edit,  @user)
  = admin_login_as_user_link(@user)


.card.mt-20
  .card-header.pt-12.pl-12
    %strong= t('activerecord.models.user')
  .card-title.mb-0
    .table-responsive
      %table.table.no-hover.table-borderless.table-striped.mb-0
        %tr
          %td= t('activerecord.shared.id')
          %td= @user.id
        %tr
          %td= t('activerecord.shared.hash_id')
          %td= @user.hash_id
        %tr
          %td= t('activerecord.attributes.user.email')
          %td= @user.email
        %tr
          %td= t('activerecord.attributes.user.role')
          %td= @user.role.text
        %tr
          %td= t('activerecord.attributes.user.locale')
          %td= @user.locale.text
        %tr
          %td= t('activerecord.shared.deleted')
          %td= boolean_icon(@user.deleted)
        %tr
          %td= t('activerecord.attributes.user.blocked')
          %td
            = boolean_icon(@user.blocked)
            - if @user.blocked?
              .badge.badge-dark= @user.blocked_reason


.mt-20
  = link_to t('admin.views.shared.all'),  admin_users_path,            class: 'btn btn-primary btn-sm' if can?(:index, @user)
  = link_to t('admin.views.shared.edit'), admin_user_edit_path(@user), class: 'btn btn-success btn-sm' if can?(:edit,  @user)
  = admin_login_as_user_link(@user)

- if can?(:view_versions, @user)
  = render partial: 'admin/versions/partials/list', locals: {versions: @versions}

  .mt-20
    = link_to t('admin.views.shared.all'),  admin_users_path,            class: 'btn btn-primary btn-sm' if can?(:index, @user)
    = link_to t('admin.views.shared.edit'), admin_user_edit_path(@user), class: 'btn btn-success btn-sm' if can?(:edit,  @user)
    = admin_login_as_user_link(@user)